@startuml
class UserBase {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>> = ""
}
class User {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>> = ""
    + HasDeleted : bool <<get>> <<set>> = false
    + <<virtual>> Chats : ICollection<Chat>? <<get>> <<set>>
}
class ChatBase {
    + Id : int <<get>> <<set>>
    + Content : string <<get>> <<set>> = ""
    + UserId : int <<get>> <<set>>
}
class Chat {
    + Id : int <<get>> <<set>>
    + Content : string <<get>> <<set>> = ""
    + UserId : int <<get>> <<set>>
    + <<virtual>> User : User? <<get>> <<set>>
}
class ChatterContext {
    + ChatterContext()
    + <<virtual>> Users : DbSet<User>? <<get>> <<set>>
    + <<virtual>> Chats : DbSet<Chat>? <<get>> <<set>>
}
DbContext <|-- ChatterContext
@enduml
