@startuml
class KeyValuePairModelDescription {
}
ModelDescription <|-- KeyValuePairModelDescription
KeyValuePairModelDescription --> "KeyModelDescription" ModelDescription
KeyValuePairModelDescription --> "ValueModelDescription" ModelDescription
@enduml
